### PR TITLE
Fixing unique_episode calculation

### LINKED ISSUE #26: unique_episode calculated wrongly
Hi,

due to a miscalculation of the episodes_per_worker_per_iteration (line 127 in logs/log.py), the unique_episode column gets wrong values. The code should look like (somehow I don't know how to format it better, sorry):

episodes_per_worker_per_iteration = df[(df["iteration"] == 0) & (df["worker"] == 0)]["episode"].max() **+ 1**
workers_count = df["worker"].max() + 1

df["unique_episode"] = df["episode"] + df["worker"] * episodes_per_worker_per_iteration + df["iteration"] * episodes_per_worker_per_iteration * workers_count

/Leon Zilverstand

### PR DESCRIPTION
**Pull request by eedlez**

### CODE REVIEW

**Comment by breadcentric** [comment]
Hello, thank you for raising this PR!
In the issue you suggested simply adding +1 to code, and in the PR there are a few new collections, a few prints and a rather convoluted new formula utilizing list generation inside. I'm not saying it's not justified to do it differently but I would like to understand the change of approach

**Comment by eedlez** [comment]
Hi,
as I also indicated in the issue, unfortunately, the simple +1 didn't fix the problem completely, so I had to find another way. I don't wanna say there is not a better way of doing this then I did, but this is the way I came up with, and it seems to work :-). If someone has a better way, feel free to comment/add/change. The prints I added for getting a better overview of what's happening, these can be removed of course if wanted.
/Leon

**Comment by eedlez** [comment]
P.S. To explain my code a bit, I simply check in the first iteration: 
- how many episodes each worker has (variable episodes_per_iteration, for example {0:4, 1:3, 2:3} for 10 episodes) 
- determine/calculate the counting starting point for every worker (variable episodes_until_worker, for example {0:0, 1:4, 2:7, 3:10}) 
- total amount of episodes (variable episodes_per_iteration, in this example 10).

Then in the formula, I do a modulo on the episode with the number of episodes for that worker (episodes_per_iteration), add the counting starting point for that worker (episodes_until_worker) plus the iteration multiplied by the number of episodes per iteration (episodes_per_iteration).

**Comment by eedlez** [comment]
@breadcentric @larsll , I'm not sure, but how should we proceed with this?

**Comment by breadcentric** [comment]
Hi I'm sorry, I've missed the notification in mail. I'll be happy to accept it if you replace prints with https://docs.python.org/3/howto/logging.html on debug level

**Comment by breadcentric** [comment]
Are you in the slack community? It's usually safest to poke me there to get something done if I don't respond long enough :)

**Comment by eedlez** [comment]
Hi @breadcentric , 
I just updated the code and pushed it, please review :-)
Yes I'm in the slack community, my name is Leon Zilverstand, what is your name, I can't find a breadcentric ;-).
Cya!
Leon

**Review by breadcentric — APPROVED** [review]

**Pull request merged**
